name: giving_bridge_frontend
description: Flutter web frontend for Giving Bridge
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  http: ^1.0.0
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  socket_io_client: ^3.1.2
  google_fonts: ^4.0.4

  # Image handling
  image_picker: ^1.0.4
  image: ^4.1.3
  path_provider: ^2.1.1
  path: ^1.8.3

  # Additional utilities
  connectivity_plus: ^4.0.2
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  integration_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  generate: true

  assets:
    - web/assets/images/hero/
